

export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const RESET = "RESET"


export const GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST"
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS"
export const GET_USER_INFO_FAIL = "GET_USER_INFO_FAIL"


export const TOGGLE_MENU = "TOGGLE_MENU"

//github

//user
export const GET_GITHUBUSER_INFO_REQUEST = "GET_GITHUBUSER_INFO_REQUEST"
export const GET_GITHUBUSER_INFO_SUCCESS = "GET_GITHUBUSER_INFO_SUCCESS"
export const GET_GITHUBUSER_INFO_FAIL = "GET_GITHUBUSER_INFO_FAIL"

//org
export const GET_GITHUBORG_INFO_REQUEST = "GET_GITHUBORG_INFO_REQUEST"
export const GET_GITHUBORG_INFO_SUCCESS = "GET_GITHUBORG_INFO_SUCCESS"
export const GET_GITHUBORG_INFO_FAIL = "GET_GITHUBORG_INFO_FAIL"



//music

//songlists
export const GET_SONGLISTS_INFO_REQUEST = "GET_SONGLISTS_INFO_REQUEST"
export const GET_SONGLISTS_INFO_SUCCESS = "GET_SONGLISTS_INFO_SUCCESS"
export const GET_SONGLISTS_INFO_FAIL = "GET_SONGLISTS_INFO_FAIL"


//disLists
export const GET_DISLISTS_INFO_REQUEST = "GET_DISLISTS_INFO_REQUEST"
export const GET_DISLISTS_INFO_SUCCESS = "GET_DISLISTS_INFO_SUCCESS"
export const GET_DISLISTS_INFO_FAIL = "GET_DISLISTS_INFO_FAIL"


//albumImg
export const GET_ALBUMIMG_INFO_REQUEST = "GET_ALBUMIMG_INFO_REQUEST"
export const GET_ALBUMIMG_INFO_SUCCESS = "GET_ALBUMIMG_INFO_SUCCESS"
export const GET_ALBUMIMG_INFO_FAIL = "GET_ALBUMIMG_INFO_FAIL"


//song
export const GET_SONG_INFO_REQUEST = "GET_SONG_INFO_REQUEST"
export const GET_SONG_INFO_SUCCESS = "GET_SONG_INFO_SUCCESS"
export const GET_SONG_INFO_FAIL = "GET_SONG_INFO_FAIL"


//lyric
export const GET_LYRIC_INFO_REQUEST = "GET_LYRIC_INFO_REQUEST"
export const GET_LYRIC_INFO_SUCCESS = "GET_LYRIC_INFO_SUCCESS"
export const GET_LYRIC_INFO_FAIL = "GET_LYRIC_INFO_FAIL"




