

export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const RESET = "RESET"


export const GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST"
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS"
export const GET_USER_INFO_FAIL = "GET_USER_INFO_FAIL"


export const TOGGLE_MENU = "TOGGLE_MENU"

//github

//user
export const GET_GITHUBUSER_INFO_REQUEST = "GET_GITHUBUSER_INFO_REQUEST"
export const GET_GITHUBUSER_INFO_SUCCESS = "GET_GITHUBUSER_INFO_SUCCESS"
export const GET_GITHUBUSER_INFO_FAIL = "GET_GITHUBUSER_INFO_FAIL"

//org
export const GET_GITHUBORG_INFO_REQUEST = "GET_GITHUBORG_INFO_REQUEST"
export const GET_GITHUBORG_INFO_SUCCESS = "GET_GITHUBORG_INFO_SUCCESS"
export const GET_GITHUBORG_INFO_FAIL = "GET_GITHUBORG_INFO_FAIL"



//music

//songLists
export const GET_SONGLISTS_REQUEST = "GET_SONGLISTS_REQUEST"
export const GET_SONGLISTS_SUCCESS = "GET_SONGLISTS_SUCCESS"
export const GET_SONGLISTS_FAIL = "GET_SONGLISTS_FAIL"


//disLists
export const GET_DISLISTS_REQUEST = "GET_DISLISTS_REQUEST"
export const GET_DISLISTS_SUCCESS = "GET_DISLISTS_SUCCESS"
export const GET_DISLISTS_FAIL = "GET_DISLISTS_FAIL"


//song
export const GET_SONG_REQUEST = "GET_SONG_REQUEST"
export const GET_SONG_SUCCESS = "GET_SONG_SUCCESS"
export const GET_SONG_FAIL = "GET_SONG_FAIL"


//lyric
export const GET_LYRIC_REQUEST = "GET_LYRIC_REQUEST"
export const GET_LYRIC_SUCCESS = "GET_LYRIC_SUCCESS"
export const GET_LYRIC_FAIL = "GET_LYRIC_FAIL"




