

export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const RESET = "RESET"


export const GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST"
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS"
export const GET_USER_INFO_FAIL = "GET_USER_INFO_FAIL"


export const TOGGLE_MENU = "TOGGLE_MENU"


export const GET_GITHUBUSER_INFO_REQUEST = "GET_GITHUBUSER_INFO_REQUEST"
export const GET_GITHUBUSER_INFO_SUCCESS = "GET_GITHUBUSER_INFO_SUCCESS"
export const GET_GITHUBUSER_INFO_FAIL = "GET_GITHUBUSER_INFO_FAIL"

export const GET_GITHUBORG_INFO_REQUEST = "GET_GITHUBORG  _INFO_REQUEST"
export const GET_GITHUBORG_INFO_SUCCESS = "GET_GITHUBORG  _INFO_SUCCESS"
export const GET_GITHUBORG_INFO_FAIL = "GET_GITHUBORG _INFO_FAIL"

